server:
  port: 8080
  servlet:
    session:
      timeout: 10h

spring:
  output:
    ansi:
      enabled: always
  main:
    banner-mode: off

  web:
    resources:
      static-locations: "file:./front/docs"
